# Generated by Django 4.0.4 on 2022-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choochoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathsegment',
            options={'verbose_name': 'Path', 'verbose_name_plural': 'Paths'},
        ),
    ]
