# Generated by Django 4.0.4 on 2022-04-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choochoo_app', '0003_order_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Train', 'verbose_name_plural': 'Trains'},
        ),
    ]
